version: "3.8"
services:
  zero1:
    container_name: FJZero
    image: dgraph/dgraph:v21.03.0
    working_dir: /data/zero1
    ports:
      - 5080:5080
      - 6080:6080
    labels:
      cluster: test
      service: zero1
    volumes:
      - data-volume:/dgraph
    command: dgraph zero --logtostderr -v=2 --bindall --expose_trace --profile_mode block --block_rate 10 --my=zero1:5080

  alpha1:
    container_name: FJAlpha
    image: dgraph/dgraph:v21.03.0
    working_dir: /data/alpha1
    volumes:
      - data-volume:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    labels:
      cluster: test
      service: alpha1
    command: dgraph alpha  --zero=zero1:5080 --expose_trace
      --profile_mode block --block_rate 10 --logtostderr -v=2 --my=alpha1:7080
      --security "whitelist=0.0.0.0/0"
      --graphql "lambda-url=http://lambda:8686/graphql-worker; extensions=false;"
      --trace "ratio=1.0;"
  lambda:
    container_name: FJLambda
    image: dgraph/dgraph-lambda:1.2.4
    labels:
      cluster: test
    ports:
      - 8686:8686
    depends_on:
      - alpha1
    environment:
      DGRAPH_URL: http://alpha1:8080
    volumes:
      - type: bind
        source: ./dist/LambdaBundle.js
        target: /app/script/script.js
        read_only: true
volumes:
  data-volume:
